# -*- coding: utf-8 -*-
"""tools.documentation.build — Markdown aus den Sprachdaten erzeugen.

Aufruf:
    python3 -m tools.documentation build          alles erzeugen
    python3 -m tools.documentation build --check  nur pruefen, ob aktuell

Erzeugt:
    docs/generated/de/lexicon/<lemma>.md     Detailseite je Lexem (deutsch)
    docs/generated/en/lexicon/<lemma>.md     Detailseite je Lexem (englisch)
    docs/generated/de/lexicon/INDEX.md       Gesamtverzeichnis
    docs/generated/en/lexicon/INDEX.md
    docs/generated/de/BEFUNDE.md             Befundregister
    docs/generated/de/PARADIGMEN.md          Deklinations- und Konjugationstabellen

Nicht erzeugt werden die handgeschriebenen Kapitel unter docs/de und docs/en —
diese beschreiben die Grammatik und bleiben Autorenarbeit.
"""

import json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
LANG = os.path.join(ROOT, "language")
GEN = os.path.join(ROOT, "docs", "generated")

KOPF_DE = ("<!-- AUTO-GENERATED — DO NOT EDIT DIRECTLY -->\n"
           "<!-- Erzeugt von tools/documentation/build.py aus language/. "
           "Aenderungen gehoeren in die Daten, nicht in diese Datei. -->\n\n")
KOPF_EN = ("<!-- AUTO-GENERATED — DO NOT EDIT DIRECTLY -->\n"
           "<!-- Generated by tools/documentation/build.py from language/. "
           "Edit the data, not this file. -->\n\n")

KASUS_DE = {"nom": "Nominativ", "akk": "Akkusativ", "dat": "Dativ", "gen": "Genitiv"}
KASUS_EN = {"nom": "nominative", "akk": "accusative", "dat": "dative", "gen": "genitive"}
GENUS_DE = {"M": "maskulin", "F": "feminin", "N": "neutrum"}
GENUS_EN = {"M": "masculine", "F": "feminine", "N": "neuter"}
TEMPUS_DE = {"präs": "Gegenwart", "vgh": "Vergangenheit", "fut": "Zukunft",
             "praesens": "Gegenwart", "vergangenheit": "Vergangenheit", "zukunft": "Zukunft"}


def _load(*parts):
    with open(os.path.join(LANG, *parts), encoding="utf-8") as f:
        return json.load(f)


def _schreibe(pfad, text, geschrieben, check):
    os.makedirs(os.path.dirname(pfad), exist_ok=True)
    if check:
        if not os.path.exists(pfad):
            geschrieben.append(("FEHLT", pfad))
        elif open(pfad, encoding="utf-8").read() != text:
            geschrieben.append(("VERALTET", pfad))
        else:
            geschrieben.append(("OK", pfad))
        return
    with open(pfad, "w", encoding="utf-8") as f:
        f.write(text)
    geschrieben.append(("OK", pfad))


def _kasustabelle(formen, sprache="de"):
    if not formen:
        return None
    kas = KASUS_DE if sprache == "de" else KASUS_EN
    hat_pl = any(k.endswith("_pl") for k in formen)
    zeilen = ["| " + ("Kasus" if sprache == "de" else "Case") + " | Singular"
              + (" | Plural |" if hat_pl else " |"),
              "|---|---|" + ("---|" if hat_pl else "")]
    for k in ("nom", "akk", "dat", "gen"):
        sg = formen.get(f"{k}_sg")
        pl = formen.get(f"{k}_pl")
        if sg is None and pl is None:
            continue
        zeile = f"| {kas[k]} | {sg or '—'}"
        zeile += f" | {pl or '—'} |" if hat_pl else " |"
        zeilen.append(zeile)
    return "\n".join(zeilen) if len(zeilen) > 2 else None


def lexem_seite_de(e, befunde, saetze_nach_lexem):
    t = [KOPF_DE, f"# {e['lemma']}\n"]
    t.append(f"**{e['de']['short']}** — {e['de']['definition']}\n")
    t.append("| Feld | Wert |\n|---|---|")
    t.append(f"| ID | `{e['lexeme_id']}` |")
    t.append(f"| Wortart | {e['wortart']}"
             + (f" ({e['grammatische_kategorie']})" if e["grammatische_kategorie"] else "") + " |")
    g = e["grammatik"]
    if g.get("genus"):
        t.append(f"| Geschlecht | {GENUS_DE.get(g['genus'], g['genus'])} |")
    if g.get("klasse"):
        t.append(f"| Klasse | {g['klasse']} |")
    if g.get("verbwurzel"):
        t.append(f"| Verbwurzel | {g['verbwurzel']}- |")
    if g.get("konjugationsklasse"):
        t.append(f"| Konjugation | {g['konjugationsklasse']} |")
    if g.get("rektion"):
        t.append(f"| Rektion | {', '.join(KASUS_DE.get(k, k) for k in g['rektion'])} |")
    t.append(f"| Status | {e['status']} |")
    t.append(f"| Häufigkeit | {e['haeufigkeit']} |")
    if e["domaenen"]:
        t.append(f"| Domäne | {', '.join(e['domaenen'])} |")
    t.append(f"| Quelle | {e['qualitaet']['quelle']} |")
    t.append("")

    t.append("## Englisch\n")
    t.append(f"**{e['en']['short'] or '—'}**"
             + (f" — {e['en']['definition']}" if e["en"]["definition"] else "")
             + f"  \n*(Übersetzungsstatus: {e['en']['status']}; "
               f"abgeleitet aus der deutschen kanonischen Bedeutung)*\n")

    tab = _kasustabelle(g.get("kasusformen"), "de")
    if tab and e["wortart"] == "nomen":
        t.append("## Deklination\n"); t.append(tab); t.append("")
    if e["wortart"] == "verb" and g.get("unregelmaessige_formen"):
        t.append("## Konjugation\n")
        formen = g["unregelmaessige_formen"]
        personen = ["1sg", "2sg", "3sg", "1pl", "2pl", "3pl"]
        tempora = [k for k in formen if isinstance(formen[k], dict)]
        t.append("| Person | " + " | ".join(TEMPUS_DE.get(x, x) for x in tempora) + " |")
        t.append("|---" * (len(tempora) + 1) + "|")
        for p in personen:
            t.append(f"| {p} | " + " | ".join(formen[x].get(p, "—") for x in tempora) + " |")
        t.append("")
        if g.get("infinitiv"):
            t.append(f"Infinitiv: **{g['infinitiv']}** · Partizip: **{g.get('partizip', '—')}**\n")
    if e["wortart"] == "adjektiv" and g.get("steigerung"):
        t.append("## Steigerung\n")
        t.append(f"- Komparativ (prädikativ): **{g['steigerung']['komparativ']}**")
        t.append(f"- Superlativ (prädikativ): **{g['steigerung']['superlativ']}**\n")

    ph = e["phonologie"]
    t.append("## Lautung und Schrift\n")
    t.append(f"- Phonemfolge: {' · '.join(ph['phonemfolge'])}")
    t.append(f"- Silbifizierung: "
             + (" · ".join(ph["silbifizierung"]) if ph["silbifizierung"]
                else f"**mehrdeutig** ({', '.join(ph['silbifizierung_kandidaten'] or [])}) — Befund L-09"))
    t.append(f"- Phonotaktik: {ph['phonotaktik_status']}"
             + ("  (Silbenform von §5.1 nicht gelistet — Befund K-01)"
                if ph["phonotaktik_status"] == "K-01" else ""))
    t.append(f"- Orbis Manus: {e['manus']['status']}"
             + (f" (mehrdeutig, {e['manus']['ambiguitaet_anzahl']} Zerlegungen)"
                if e["manus"]["ambiguitaet"] else ""))
    t.append("")

    sem = e["semantik"]
    if sem["concept_ids"] or sem["relationen"] or sem["synonyme"]:
        t.append("## Bedeutung\n")
        if sem["concept_ids"]:
            t.append(f"- Konzept(e): {', '.join(f'`{c}`' for c in sem['concept_ids'])}")
        for rel in sem["relationen"]:
            t.append(f"- {rel['typ']}: `{rel['ziel']}`"
                     + (f" — {rel['anmerkung_de']}" if rel.get("anmerkung_de") else ""))
        for syn in sem["synonyme"]:
            t.append(f"- Synonym `{syn['lexeme_id']}` ({syn['staerke']}, "
                     f"austauschbar: {syn['austauschbar']}): {syn['bedeutungsunterschied_de']}")
        t.append("")

    wf = e["wortfamilie"]
    if wf["wurzel"] or wf["abgeleitete"] or wf["komposita"]:
        t.append("## Wortfamilie\n")
        if wf["wurzel"]:
            t.append(f"- Wurzel: **{wf['wurzel']}**")
        if wf["abgeleitete"]:
            t.append(f"- Ableitungen: {', '.join(wf['abgeleitete'])}")
        if wf["komposita"]:
            t.append(f"- Komposita: {', '.join(wf['komposita'])}")
        t.append("")

    et = e["etymologie"]
    t.append("## Etymologie\n")
    if et["status"] == "unknown":
        t.append("Keine Herleitung dokumentiert. Die Referenzgrammatik nennt für dieses "
                 "Lexem keine Proto-Orbis-Form; sie wird nicht rekonstruiert "
                 "(Status: `unknown`).\n")
    else:
        t.append(f"- Status: {et['status']}")
        if et["proto_form"]:
            t.append(f"- Proto-Orbis: *{et['proto_form']}*")
        if et["lautgesetze"]:
            t.append(f"- Lautgesetze: {', '.join(et['lautgesetze'])}")
        t.append("")

    bsp = saetze_nach_lexem.get(e["lexeme_id"], [])[:5]
    if bsp:
        t.append("## Beispielsätze\n")
        for s in bsp:
            t.append(f"- **{s['orbis']}**  \n  {s['de']}  \n  *{s['en']}*  \n  `{s['id']}`")
        t.append("")

    q = e["qualitaet"]
    t.append("## Prüfstand\n")
    t.append(f"- Validatorstatus: {q['validatorstatus']}")
    if q["offene_befunde"]:
        t.append("- Offene Befunde:")
        for b in q["offene_befunde"]:
            f = befunde.get(b)
            t.append(f"  - **{b}** — {f['titel_de']}" if f else f"  - **{b}**")
    t.append(f"- Letzte Prüfung: {q['letzte_pruefung']}")
    t.append("")
    return "\n".join(t)


def lexem_seite_en(e, saetze_nach_lexem):
    t = [KOPF_EN, f"# {e['lemma']}\n"]
    t.append(f"**{e['en']['short'] or '—'}**"
             + (f" — {e['en']['definition']}" if e["en"]["definition"] else "") + "\n")
    t.append("> The German entry is authoritative. This page is derived from it "
             "(see `TRANSLATION_POLICY.md`).\n")
    t.append("| Field | Value |\n|---|---|")
    t.append(f"| ID | `{e['lexeme_id']}` |")
    t.append(f"| Part of speech | {e['wortart']} |")
    g = e["grammatik"]
    if g.get("genus"):
        t.append(f"| Gender | {GENUS_EN.get(g['genus'], g['genus'])} |")
    if g.get("klasse"):
        t.append(f"| Class | {g['klasse']} |")
    t.append(f"| Status | {e['status']} |")
    t.append(f"| German gloss (canonical) | {e['de']['short']} |")
    t.append("")
    tab = _kasustabelle(g.get("kasusformen"), "en")
    if tab and e["wortart"] == "nomen":
        t.append("## Declension\n"); t.append(tab); t.append("")
    bsp = saetze_nach_lexem.get(e["lexeme_id"], [])[:5]
    if bsp:
        t.append("## Examples\n")
        for s in bsp:
            t.append(f"- **{s['orbis']}**  \n  *{s['en']}*  \n  `{s['id']}`")
        t.append("")
    return "\n".join(t)


def build(check=False):
    idx = _load("lexicon", "index.json")
    befunde = {f["id"]: f for f in _load("findings", "findings.json")["findings"]}
    korpus = _load("corpus", "tests", "testkorpus-0_1.json")
    saetze_nach_lexem = {}
    for s in korpus["saetze"]:
        if not s["orbis"]:
            continue
        for lid in s["lexeme"]:
            saetze_nach_lexem.setdefault(lid, []).append(s)

    geschrieben = []
    zeilen_de, zeilen_en = [], []
    for eintrag in idx["eintraege"]:
        e = _load("lexicon", eintrag["datei"])
        name = os.path.splitext(os.path.basename(eintrag["datei"]))[0]
        _schreibe(os.path.join(GEN, "de", "lexicon", name + ".md"),
                  lexem_seite_de(e, befunde, saetze_nach_lexem), geschrieben, check)
        _schreibe(os.path.join(GEN, "en", "lexicon", name + ".md"),
                  lexem_seite_en(e, saetze_nach_lexem), geschrieben, check)
        zeilen_de.append(f"| [{e['lemma']}]({name}.md) | {e['wortart']} | "
                         f"{e['de']['short']} | {e['status']} |")
        zeilen_en.append(f"| [{e['lemma']}]({name}.md) | {e['wortart']} | "
                         f"{e['en']['short'] or '—'} | {e['status']} |")

    _schreibe(os.path.join(GEN, "de", "lexicon", "INDEX.md"),
              KOPF_DE + f"# Orbis-Lexikon — Gesamtverzeichnis\n\n"
              f"{idx['anzahl']} Einträge (Lexicon {idx['lexicon_version']}, "
              f"Grammar {idx['grammar_version']}).\n\n"
              "| Lemma | Wortart | Bedeutung | Status |\n|---|---|---|---|\n"
              + "\n".join(sorted(zeilen_de)) + "\n", geschrieben, check)
    _schreibe(os.path.join(GEN, "en", "lexicon", "INDEX.md"),
              KOPF_EN + f"# Orbis Lexicon — Index\n\n{idx['anzahl']} entries "
              f"(Lexicon {idx['lexicon_version']}, Grammar {idx['grammar_version']}).\n\n"
              "> Derived from the German entries, which are authoritative.\n\n"
              "| Lemma | Part of speech | Meaning | Status |\n|---|---|---|---|\n"
              + "\n".join(sorted(zeilen_en)) + "\n", geschrieben, check)

    # Befundregister
    fz = ["| ID | Typ | Priorität | Titel | Betroffene Paragraphen | Status |",
          "|---|---|---|---|---|---|"]
    for f in sorted(befunde.values(), key=lambda x: (x["prioritaet"], x["id"])):
        fz.append(f"| {f['id']} | {f['typ_label_de']} | {f['prioritaet']} | {f['titel_de']} | "
                  f"{', '.join(f['affected_rules'])} | {f['status']} |")
    _schreibe(os.path.join(GEN, "de", "BEFUNDE.md"),
              KOPF_DE + "# Befundregister\n\nAlle dokumentierten Regelkonflikte, "
              "Regellücken, Unklarheiten und Wortschatzbefunde.\n\n"
              + "\n".join(fz) + "\n\nQuelle: `language/findings/findings.json`.\n",
              geschrieben, check)

    # Paradigmen
    sys.path.insert(0, ROOT)
    from tools.validator.reports import table_45, table_verb
    from tools.validator.data import IRREGULAR_VERBS
    pz = [KOPF_DE, "# Paradigmen\n",
          "## Die 45 regulären Nomenendungen\n",
          "Prüfstamm `pren-` ([TESTFORM], kein Wort des Wortschatzes).\n",
          "| Klasse | Endung | Nom Sg | Akk Sg | Dat Sg | Gen Sg | Nom Pl | Akk Pl | Dat Pl | Gen Pl |",
          "|---|---|---|---|---|---|---|---|---|---|"]
    for kl, end, *formen in table_45():
        pz.append(f"| {kl} | -{end} | " + " | ".join(formen) + " |")
    pz.append("\n## Regelmäßiges Verb (milk-)\n")
    pz.append("| Person | Gegenwart | Vergangenheit | Zukunft |\n|---|---|---|---|")
    zeilen = {}
    for t, p, f in table_verb("milk"):
        zeilen.setdefault(p, {})[t] = f
    for p in ("1sg", "2sg", "3sg", "1pl", "2pl", "3pl"):
        pz.append(f"| {p} | {zeilen[p]['präs']} | {zeilen[p]['vgh']} | {zeilen[p]['fut']} |")
    for root in IRREGULAR_VERBS:
        pz.append(f"\n## {IRREGULAR_VERBS[root]['inf']} "
                  f"({IRREGULAR_VERBS[root]['bedeutung']}) — unregelmäßig\n")
        pz.append("| Person | Gegenwart | Vergangenheit | Zukunft |\n|---|---|---|---|")
        zeilen = {}
        for t, p, f in table_verb(root):
            zeilen.setdefault(p, {})[t] = f
        for p in ("1sg", "2sg", "3sg", "1pl", "2pl", "3pl"):
            pz.append(f"| {p} | {zeilen[p]['präs']} | {zeilen[p]['vgh']} | {zeilen[p]['fut']} |")
    _schreibe(os.path.join(GEN, "de", "PARADIGMEN.md"), "\n".join(pz) + "\n",
              geschrieben, check)

    probleme = [g for g in geschrieben if g[0] != "OK"]
    if check:
        if probleme:
            print(f"{len(probleme)} generierte Dateien sind nicht aktuell:")
            for status, p in probleme[:20]:
                print(f"  [{status}] {os.path.relpath(p, ROOT)}")
            return 1
        print(f"Alle {len(geschrieben)} generierten Dateien sind aktuell.")
        return 0
    print(f"{len(geschrieben)} Dateien erzeugt unter docs/generated/")
    return 0
